SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(DAILY_FEE*30*(100-DISCOUNT_RATE)/100) AS FEE
FROM
	CAR_RENTAL_COMPANY_CAR C
    	JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    		ON C.CAR_TYPE = DP.CAR_TYPE
    	JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    		ON C.CAR_ID = RH.CAR_ID
WHERE
	C.CAR_TYPE IN ('세단', 'SUV')
    	AND C.CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE (START_DATE LIKE '2022-11-%' OR END_DATE LIKE '2022-11-%')
            	OR (START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-30')
    	)
    AND DP.DURATION_TYPE = '30일 이상'
    AND C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE/100) >= 500000
    AND C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE/100) < 2000000

GROUP BY CAR_ID

ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC