select PRICE_GROUP*10000 as PRICE_GROUP , count(*) as PRODUCTS
from(select PRODUCT_ID, PRODUCT_CODE, PRICE, floor(PRICE/10000) as PRICE_GROUP
from PRODUCT) as p
group by PRICE_GROUP
order by PRICE_GROUP 